// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "user": Application Media Types
//
// Command:
// $ goagen
// --design=goa-user/design
// --out=$(GOPATH)/src/goa-user
// --version=v1.2.0-dirty

package app

// User (default view)
//
// Identifier: application/example.user+json; view=default
type ExampleUser struct {
	// User email
	Email *string `form:"email,omitempty" json:"email,omitempty" xml:"email,omitempty"`
	// User ID
	ID *int `form:"id,omitempty" json:"id,omitempty" xml:"id,omitempty"`
	// User name
	Username *string `form:"username,omitempty" json:"username,omitempty" xml:"username,omitempty"`
}
