// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "user": Application User Types
//
// Command:
// $ goagen
// --design=goa-user/design
// --out=$(GOPATH)/src/goa-user
// --version=v1.2.0-dirty

package app
